### PR TITLE
Implement doorbell silencing.

### PR DESCRIPTION
**Pull request by dermotduffy**
Add basic support for silence mode of doorbells (both chimes, and chimes & calls). The Arlo API is a little confusing in this regard, and I suspect there's more flexibility possible (e.g. disable of traditional chimes, but not Arlo chimes) -- but this is all I was able to figure out from my setup, and to test.

### CODE REVIEW

**Comment by twrecked** [comment]
Sorry for the delay, real work got in the way. I'll get round to looking at this over the next few days.

**Comment by dakesson** [comment]
Really nice, hope this gets in :)

**Comment by twrecked** [comment]
Thanks for this!

**Comment by dakesson** [comment]
I just tested it without getting a switch for silence - others worked as expected. Doorbell model: AAD1001
HW version 1.3, 

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True

**Comment by marcandre83** [comment]
I just tried to enable the doorbell_silence switches, unfortunately getting this error:

`2020-07-30 20:40:37 ERROR (MainThread) [homeassistant.components.switch] Error while setting up aarlo platform for switch
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/switch.py", line 93, in async_setup_platform
    devices.append(AarloSilentModeChimeSwitch(doorbell))
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/switch.py", line 388, in __init__
    doorbell.name), doorbell, block_call=False)
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/switch.py", line 332, in __init__
    super().__init__(name, "doorbell")
TypeError: __init__() missing 1 required positional argument: 'icon'`

**Comment by twrecked** [comment]
Crap. That'll be a merge issue. I added support for IDs as device names and forgot update this piece.

**Comment by marcandre83** [comment]
thanks for the quick reply! if you need any more information to update it, tell me and I'll take a look into it

**Comment by twrecked** [comment]
Fixed by #289 in 0.7.alpha.8.1

**Pull request merged**
