### PR TITLE
Merge branch version-0.6.x into master

### PR DESCRIPTION
**Pull request by sebr**

### CODE REVIEW

**Comment by twrecked** [comment]
I owe you an apology, I didn't explain myself very well. I was wondering if you could merge the Arlo Ultra SpotLight changes into this repository/branch:
- https://github.com/twrecked/pyaarlo/tree/master


Right now I have 3 branches on the go:
- https://github.com/twrecked/hass-aarlo/tree/version-0.6.x
  Source of the 0.6.18.* builds. I'm only putting bug fixes in here. Although if somebody is kind enough to contribute I'm not going to say no!

- https://github.com/twrecked/hass-aarlo/tree/master
  Source of the 0.6.89.beta* builds and soon-to-be 0.7.* builds.

- https://github.com/twrecked/pyaarlo/tree/master
  hass-aarlo's sister repository, a CLI only version of the code. I test code in here and then bring it across to hass-aarlo's master branch. Right now this has several features I've not brought over to `hass-aarlo` because I'm finishing up the testing. My plan is to bring over the latest set of changes sometime this weekend.

You might have noticed the [`hass-aarlo:custom_components/aarlo/pyaarlo`](https://github.com/twrecked/hass-aarlo/tree/master/custom_components/aarlo/pyaarlo) and [`pyaarlo:pyaarlo`](https://github.com/twrecked/pyaarlo/tree/master/pyaarlo) directories are (almost) identical. My original plan was to create a PyPi package for `pyaarlo` and put it in as a dependency for `hass-aarlo`, I just never got round to it. I might still create the package - I now have the `setup.py` in place and you can `pip install` from `git` - but I think I'll keep the `pyaarlo` in `hass-aarlo`.

Once again, apologies for my lack of clarity, but if it's any consolation I think the diff for this PR will probably work.

**Comment by sebr** [comment]
No sweat @twrecked - I've forward ported to twrecked/pyaarlo#28

Regarding beta versions, it's not clear that these are pre-release. I would suggest two changes to make this clearer:

### Follow `semver` naming
[`semver`](https://semver.org/spec/v2.0.0.html#spec-item-9) can be considered a sort of defacto release naming spec. I'm not a heavy follower of the python community, but hopefully it's similar. In your case, release naming would change from `0.6.18.x` to `0.7.0-alpha.1`, `0.7.0-alpha.2` etc. This makes it clear that the pre-release is for the `0.7.x`.

### Select "pre-release" when creating a release

This tells HACS to also hide these releases from the masses unless the user opts into betas.

Select the "This is a pre-release" checkbox when drafting a new GH release:

Screen Shot 2020-04-26 at 8 44 22 pm

This also  clearly marks releases as pre-releases:

Screen Shot 2020-04-26 at 8 45 13 pm

**Comment by twrecked** [comment]
Thank you for doing that. Thanks for the release info, I will be releasing `0.7.0-alpha.1` later today!

**Comment by sebr** [comment]
Pleasure @twrecked, happy to help.

What would you like to do with this PR?

**Comment by twrecked** [comment]
I'm just going to close it. I'm planning on merging pyaarlo back into this code this afternoon.

Did you the issue raised about Arlo ultra sirens? Do you mind taking a look?

**Comment by sebr** [comment]
No probs, do you want me to cherry-pick e6a315e to master so it's included in future 0.7.x releases?

**Comment by twrecked** [comment]
Thanks for asking but no. The non spotlight bits are already in `pyaarlo`.

I just did a test merge back and the diff looks ok.

**Pull request closed without merging**
