### PR TITLE
WIP: Config flow setup

### PR DESCRIPTION
**Pull request by NickM-27**
• set config flow to true
• add basic template for config flow

This may be helpful: 
https://developers.home-assistant.io/docs/auth_auth_module
https://developers.home-assistant.io/docs/config_entries_index
https://developers.home-assistant.io/docs/data_entry_flow_index

### CODE REVIEW

**Comment by NickM-27** [comment]
@twrecked So things are looking pretty good, it comes with the 5 fields. Now just need to figure out best logic for __init__ to figure out if it should pull from the internal config or the configuration.yaml

Let me know when you have some time to play around with it and what you think, but I would say it should be pretty close.

**Comment by twrecked** [comment]
Firstly, apologies for the delay getting to this, I've been chasing down a bug in my real job.

I'll look at this later today. And thanks for doing this.

**Comment by NickM-27** [comment]
Sure no problem, feel free to ping me if there's any questions. Like I said in the comment I added those fields (maybe it would be better to do different ones after you look, hopefully my code is readable / easy to follow) and the only thing left to do is in the __init__ to handle the internal config if it is available for those 5 fields but also still support the other fields in configuration.yaml

**Comment by twrecked** [comment]
Thanks for this, and looks good.

I'll commit this and play around with it at this end - to familiarise myself with config flow and to work out the "config merge" mechanism.

**Pull request merged**
