### PR TITLE
Allow auth_host to be configurable

### PR DESCRIPTION
**Pull request by jesserockz**
With the changes in #191 the auth host was hardcoded to the production server only. This allows the user to override it to another server e.g staging `https://ocapi-app-qa.arlo.com`

### CODE REVIEW

**Comment by jesserockz** [comment]
I have made the same changes in twrecked/pyaarlo#27

**Comment by twrecked** [comment]
Thanks for doing this. I will commit it, but one question, how would the user know to use another server?

**Comment by jesserockz** [comment]
The staging backend always uses another auth server. Maybe the servers could be coded in pyaarlo and the user is able to choose the environment which would switch them all?

**Comment by Turtlepaw** [comment]
@jesserockz did you manage to get the staging server working with aarlo?

**Comment by jesserockz** [comment]
> @jesserockz did you manage to get the staging server working with aarlo?

Yes it was working, but I no longer use Arlo devices via the cloud. I have since moved to using scrypted for arlo and keep everything local =)

**Pull request merged**
