### PR TITLE
Fix #528

### LINKED ISSUE #528: Component Doesn't Have Devices Defined in Home Assistant?
Just curious, I was wondering if there are any plans to add a HA device for each Arlo Device. For example I have my Driveway Cam which of course has all of its associated entities but there is no HA device which contains those entities. I think it would be nice to have `Driveway Cam` device which has `control`, `sensor`, and `diagnostic` entities categorized to make them easier to work with.

The reason I am asking is because I just wanted to make sure there isn't a reason this hasn't been done already.

### PR DESCRIPTION
**Pull request by NickM-27**
Fix for #528 
• Create consts file and cleanup init
• Add device info calls to all entities that have that available

### CODE REVIEW

**Comment by NickM-27** [comment]
@twrecked If this is good, now targeted at 0.8.0, this should be good to merge as it does not interfere with existing logic. Then I can start a PR for the config flow but that'll likely require your help as it is proving difficult for me to wrap my head around

**Comment by twrecked** [comment]
Just checking - it's been a long day at my real job - but we only need to pull this request?

In the mean time, I'll check them out and take a look.

**Comment by NickM-27** [comment]
@twrecked this is the only one ready. It can be merged and will not have an effect either way (but good to have to done) and then the WIP for config flow I'll definitely need some help with whenever you have some free time

**Comment by twrecked** [comment]
One thing, you need to add this to `const.py`. The merge checks failed on it.

```python
from datetime import timedelta
```

**Comment by NickM-27** [comment]
Sweet, should hopefully be good now

**Pull request merged**
