### PR TITLE
Add support for custom_updater and the tracker card

### PR DESCRIPTION
**Pull request by rccoleman**
This PR adds support for tracking updates to the component and card and allowing for easier updates via the Lovelace tracker card.  The following changes need to be made:

In configuration.yaml:

```
custom_updater:
  track:
    - components
    - cards
  component_urls:
    - https://raw.githubusercontent.com/rccoleman/hass-aarlo/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/rccoleman/hass-aarlo/master/custom_cards.json
```

In ui-lovelace.yaml:

```
resources:
  - type: module
    url: /customcards/aarlo-glance.js?track=true
```

Ideally the components and cards would be added to the official list to avoid the need to make these changes:

> https://raw.githubusercontent.com/custom-cards/information/master/repos.json
> https://raw.githubusercontent.com/custom-components/information/master/repos.json

as described here: https://github.com/custom-components/custom_updater/wiki/How-it-works

Version numbers and repo file locations will obviously need to be changed.

### CODE REVIEW

**Comment by rpitera** [comment]
```
resources:
  - type: module
    url: /customcards/aarlo-glance.js?track=true
```

Should be 

```
resources:
  - url: /customcards/aarlo-glance.js?track=true
    type: module
```

**Comment by rccoleman** [comment]
Does order matter for this, other then stylistically?  I think I’ve seen it both ways.

**Comment by rpitera** [comment]
I've only seen it with the URL first in all the custom cards (of which I probably have too many!) that I use.

**Comment by rccoleman** [comment]
All of mine are consistently the other way, so... :) I used to have a mix and chose to make them all consistent before this pull. The user has to add these lines manually, so they can choose their own style.

**Comment by rpitera** [comment]
Either way, thanks for your PR to add tracking support.  This project has totally changed the way I feel about my Arlo cams in HA, so being able to track development is important.  Appreciate your PR.

**Comment by twrecked** [comment]
How do I go about merging this into the my code - I'm seeing something about a 'draft pull request'?

Forgive my ignorance, I'm a total newbie to this whole github thing.

**Comment by rccoleman** [comment]
I'm new at this as well.  Let me see how I can convert it to a real full request.  Keep in mind that a bunch of stuff needs to be configured to point to your repo.

**Comment by twrecked** [comment]
Sorry it took so long - been painting like crazy at home all week - but it should be merged now.

**Comment by rccoleman** [comment]
Woohoo!

**Pull request merged**
