### PR TITLE
Add Pro 4 & Essential capabilities

### PR DESCRIPTION
**Pull request by jesserockz**
Arlo Pro 4 model id starts with `VMC4041`
Arlo Essential model id starts with `VMC2030`

Pro 4 has the same capabilities as the Pro 3, but with WiFi direct connection so may or may not have a base station.
Essential has the same capabilities as Pro 4 but only a 1080p camera and non-removable battery

twrecked/pyaarlo#51

### CODE REVIEW

**Comment by twrecked** [comment]
Thanks for this!

**Comment by twrecked** [comment]
Do we need to modify `pyaarlo/__init__.py` to create a fake base station for these devices?

**Comment by jesserockz** [comment]
Oh yes, I will add that soon.

**Comment by twrecked** [comment]
Thanks!

**Pull request merged**
